export const SET_LOADING = "SET_LOADING";
export const SET_ERROR = "SET_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";

//AUTH ACTIONS
export const SIGNUP_USER = "SIGNUP_USER";
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";

//DATA FETCH ACTIONS
export const GET_UNIS = "GET_UNIS";
export const SET_CURRENT_UNI = "SET_CURRENT_UNI";
export const GET_UNI_COURSES = "GET_UNI_COURSES";
export const SET_CURRENT_COURSE = "SET_CURRENT_COURSE"
export const GET_COURSE_BY_ID = "GET_COURSE_BY_ID";
export const GET_FILES_BY_COURSE = "GET_FILES_BY_COURSE";

//DATA UPDATE ACTIONS

//STYLE ACTIONS
export const SET_CURRENT_LAYOUT = "SET_CURRENT_LAYOUT";
